### ISSUE TITLE
TSL2561 error: Too much data to fit in transmitter buffer

### ISSUE THREAD

**Issue by derandiunddasbo** [esphome/ESPHome-Core#260]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** n/A

**ESP (ESP32/ESP8266/Board/Sonoff):** ESP32 / nodemcu-32s

**Affected component:** https://esphomelib.com/esphomeyaml/components/sensor/tsl2561.html

**Description of problem:**
After running fine for some months, a TSL2561 Ambient Light Sensor isn't initialized properly at reboot. The log shows an error `Too much data to fit in transmitter buffer for address 0x39`. I don't know, what this error means. Is the sensor recognized at all? Does it send wrong data? Or maybe is it just bad wiring?

Could somebody please enlighten me, how to interpret this error message? :-)

**Problem-relevant YAML-configuration entries:**
```yaml
i2c:
  sda: 21
  scl: 22
  scan: False

sensor:
  - platform: tsl2561
    name: "EG Aquarium Helligkeit"
    address: 0x39
    update_interval: 15s

```

**Traceback (if applicable):**

```
[18:52:28][C][sensor.tsl2561:036]: Setting up TSL2561...
[18:52:28][C][sensor.tsl2561:037]:     Address: 0x39
[18:52:28][W][i2c:084]: Too much data to fit in transmitter buffer for address 0x39
[18:52:28][E][sensor.tsl2561:040]: Communication with TSL2561 on address 0x39 failed!
[18:52:28][E][component:162]: Component was marked as failed.
```

**Additional information:**
