### ISSUE TITLE
restore_mode option doesn't restore switch state

### ISSUE THREAD

**Issue by vevsvevs** [esphome/ESPHome-Core#460]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Hass.io (HassOS OVA)

**ESP (ESP32/ESP8266/Board/Sonoff):**
Sonoff Basic (ESP8285)

**Affected component:**
https://esphomelib.com/esphomeyaml/components/switch/gpio.html

**Description of problem:**
`restore_mode` doesn't actually restore previous switch state, even if the option is explicitly set.

**Problem-relevant YAML-configuration entries:**
```yaml
switch:
  - platform: gpio
    name: "sonoff_kitchen_light"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
```

**Traceback (if applicable):**

```

```

**Additional information:**
