### ISSUE TITLE
esp32_ble_tracker scan_interval not used correctly

### ISSUE THREAD

**Issue by njbuch** [esphome/ESPHome-Core#464]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows, platformIO - all newest components as of today.

**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP32

**Affected component:**

esp32_ble_tracker

**Description of problem:**
When changing the scan_interval in the YAML file, the scan_interval written in the log-files does not match, and it seems that only the default value of 300s works.

**Problem-relevant YAML-configuration entries:**
```yaml
esphomeyaml:
  name: tracker
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: 'xxx'
  password: 'xxxx'

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
  scan_interval: 10s
```

**Traceback (if applicable):**

```

```

**Additional information:**
