### ISSUE TITLE
Fan  speed automation result in error while compiling

### ISSUE THREAD

**Issue by remc0** [esphome/ESPHome-Core#467]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
pip in terminal on a mac

**ESP (ESP32/ESP8266/Board/Sonoff):**
platform: ESP32
 board: lolin_d32

**Affected component:**
Speed Fan

**Description of problem:**
I'm trying to automate the fans on my convector and think my yaml is valid. esphomelib doesn't complain but the compilation fails when I want to update my ESP.

**Problem-relevant YAML-configuration entries:**
```yaml
output:
  - platform: ledc
    pin: 23
    id: gpio_23
    frequency: 25000
    bit_depth: 8
    channel: 0
  - platform: gpio
    pin: 15
    id: 'generic_out'

fan:
  - platform: speed
    output: gpio_23
    name: "Living Room Fan"
    id: fan_1
    speed:
      low: 0.05
      medium: 0.10
      high: 0.20

switch:
  - platform: output
    name: "FAN Switch"
    output: 'generic_out'

dallas:
  - pin: 17

#Individual sensors
sensor:
  - platform: dallas
    address: 0xC20000039C8F8728
    name: "Convector Livingroom Temperature"
    on_value_range:
        above: 21.5
        then:
          - fan.turn_on:
              id: fan_1
              speed: MEDIUM
```

**Traceback (if applicable):**
```
src/main.cpp: In function 'void setup()':
src/main.cpp:47:29: error: no matching function for call to 'esphomelib::fan::TurnOnAction<float>::set_speed(const char [7])'
action->set_speed("MEDIUM");
^
In file included from .piolibdeps/esphomelib/src/esphomelib/controller.h:5:0,
from .piolibdeps/esphomelib/src/esphomelib/application.h:9,
from src/main.cpp:3:
.piolibdeps/esphomelib/src/esphomelib/fan/fan_state.h:163:6: note: candidate: void esphomelib::fan::TurnOnAction<T>::set_speed(std::function<esphomelib::fan::FanSpeed(T)>&&) [with T = float]
void TurnOnAction<T>::set_speed(std::function<FanSpeed(T)> &&speed) {
^
.piolibdeps/esphomelib/src/esphomelib/fan/fan_state.h:163:6: note:   no known conversion for argument 1 from 'const char [7]' to 'std::function<esphomelib::fan::FanSpeed(float)>&&'
.piolibdeps/esphomelib/src/esphomelib/fan/fan_state.h:167:6: note: candidate: void esphomelib::fan::TurnOnAction<T>::set_speed(esphomelib::fan::FanSpeed) [with T = float]
void TurnOnAction<T>::set_speed(FanSpeed speed) {
^
.piolibdeps/esphomelib/src/esphomelib/fan/fan_state.h:167:6: note:   no known conversion for argument 1 from 'const char [7]' to 'esphomelib::fan::FanSpeed'
```

**Additional information:**
I can give more info if needed.

TIA Remco
