### ISSUE TITLE
HTW8012 / BL0937 - Power != Voltage*Current

### ISSUE THREAD

**Issue by beveradb** [esphome/esphome-core#475]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on Raspberry Pi

**ESP (ESP32/ESP8266/Board/Sonoff):**

ESP8285, inside "Slitinto" / NX-SM110 smart plug ([PCB photos here](https://photos.app.goo.gl/ideYzXKV3By36xueA))

**Affected component:**

[HLW8012](https://esphomelib.com/esphomeyaml/components/sensor/hlw8012.html)

**Description of problem:**
I spent a while tweaking the `current_resistor` and `voltage_divider` settings to try and get realistic values, and eventually found values which show the Voltage and Power correctly (I'm using a heating element and multimeter to test, and also comparing with the values recorded by Tasmota).

However, for some reason the Current value is still off, and in fact doesn't even make sense given that the Power and Voltage values are correct - I'd have assumed Power was simply V*I but in this case I seem to have a correct Voltage and Power value but incorrect Current.

I own 8 of these plugs, and the issue is the same for all of them if I use the same YAML (below), so it's not an issue with an individual plug.

Here is an example of the ESPHome log entries the device outputs:
```
[21:16:20][D][sensor.hlw8012:067]: Got power=671.3W, current=8.4A
[21:16:40][D][sensor.hlw8012:075]: Got power=672.3W, voltage=228.2V
[21:17:00][D][sensor.hlw8012:067]: Got power=674.5W, current=8.3A
[21:17:20][D][sensor.hlw8012:075]: Got power=677.0W, voltage=228.4V
[21:17:40][D][sensor.hlw8012:067]: Got power=678.6W, current=8.4A
[21:18:00][D][sensor.hlw8012:075]: Got power=679.1W, voltage=230.3V
```
during this test, that 8.4A value should actually be 2.96A.

I'm happy to have a poke around in the ESPHomeLib code to try and understand how this is supposed to work and how it can be possible that I'm getting values which don't follow P=V*I, but I thought I'd ask here in case you had any idea.

It's worth noting that this chipset is the HJL-01/BL0937-based one, which gets special treatment in Tasmota. If you take a look at [xnrg_01_hlw8012.ino](https://github.com/arendst/Sonoff-Tasmota/blob/master/sonoff/xnrg_01_hlw8012.ino#L179), there's a `hlw_model_type` which varies the default reference values significantly.

For now this is usable for rough power usage monitoring, but I don't have a huge amount of confidence in the values and would love to try and improve ESPHome to have proper support for these devices!

**Problem-relevant YAML-configuration entries:**
```yaml
sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO03
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: 0.002452
    voltage_divider: 922
    current:
      name: "Heating Switch Current"
      unit_of_measurement: A
    voltage:
      name: "Heating Switch Voltage"
      unit_of_measurement: V
    power:
      name: "Heating Switch Power"
      id: switch_power
      unit_of_measurement: W
    change_mode_every: 1
    update_interval: 1s
```

**Traceback (if applicable):**

```

```

**Additional information:**
