### ISSUE TITLE
[RGB Light Platform] Remember brightness and color after restart

### ISSUE THREAD

**Issue by pavolholes** [esphome/esphome-core#489]
**Is your feature request related to a problem/use-case? Please describe.**

Problem: I toggle on the [RGB Light platform](https://esphome.io/components/light/rgb.html), set the brightness to 50%, set the color to warm white.
Now suddenly the electricity blackout happens (caused by me playing with home automation :) ).
When the power is restored, the light is off. So I toggle it on, the brightness goes to 100% and the color is white (not warm white).

**Describe the solution you'd like**

When the powers is restored, light might be off, but when I toggle it on it would be great if it would remember the last brightness level and the color value.

**Additional context**

I'm running esphomelib v1.10.1 compiled on Feb 10 2019, 19:42:20

```
output:
  # Enable three pins as outputs with software PWM output (ESP8266) for RGB light.
  # Lower frequency from default 1000Hz to 100Hz to lower filckering sound.
  - platform: esp8266_pwm
    pin: D5 #GPIO14
    frequency: 100 Hz
    id: 'outputRgbRed'
  - platform: esp8266_pwm
    pin: D6 #GPIO12
    frequency: 100 Hz
    id: 'outputRgbGreen'
  - platform: esp8266_pwm
    pin: D7 #GPIO13
    frequency: 100 Hz
    id: 'outputRgbBlue'

light:
  # Create RGB light which will maintain output defined above.
  - platform: rgb
    id: 'lightRgb'
    name: 'Livingroom RGB light'    
    red: outputRgbRed
    green: outputRgbGreen
    blue: outputRgbBlue
```
