### ISSUE TITLE
Map Output

### ISSUE THREAD

**Issue by michaelwoods** [esphome/esphome-core#497]
I'm researching whether this library can fulfill my use case.

I have a Vornado fan that I am going to solder some GPIO pins to the buttons on the PCB. There's a power button and 4 speeds (will ignore one speed for Speed Fan support).

As this is not directly a float compatible setup, it doesn't seem currently possible to map ranges of a Float Output to multiple Binary Outputs. Is this true? If so, I'd consider extending the Float Output to accept a dictionary of outputs with ranges.

Example:
- `0.0 < speed <= 0.33`: low output pin
- `0.33 < speed <= 0.66`: med output pin
- `0.66 < speed <= 1`: high output pin

```yaml
output:
  - platform: map
    id: fan_map_output_id
    power_supply: power_button_id
    speeds:
      low:
        id: low_button_id
        range: [0.0, 0.33]
      medium:
        id: med_button_id
        range: [0.33, 0.66]
      high:
        id: high_button_id
        range: [0.66, 1]
```

Alternatively, I suppose the Speed Fan component can be modified to associate outputs with speeds.
